import { useEffect, useState } from 'react';

export type Language = 'it' | 'en' | 'es' | 'fr' | 'de' | 'pt';

const translations: Record<Language, Record<string, string>> = {
  it: {
    // Greetings
    'greeting.morning': 'Buongiorno',
    'greeting.afternoon': 'Buon pomeriggio',
    'greeting.evening': 'Buonasera',
    'greeting.hello': 'Ciao',
    'greeting.welcome': 'Bentornato su e621 Gallery',
    
    // Navigation
    'nav.gallery': 'Galleria',
    'nav.shorts': 'Shorts',
    'nav.favorites': 'Preferiti',
    
    // Actions
    'action.download': 'Download',
    'action.download.opened': 'Download aperto in nuova scheda',
    'action.download.unavailable': 'Download non disponibile',
    'action.search': 'Cerca',
    'action.search.placeholder': 'Cerca tag...',
    'action.refresh': 'Aggiorna',
    'action.refreshed': 'Galleria aggiornata',
    'action.login': 'Accedi',
    'action.logout': 'Esci',
    'action.back': 'Indietro',
    'action.close': 'Chiudi',
    
    // Likes/Favorites
    'like.added': 'Like aggiunto!',
    'like.removed': 'Like rimosso',
    'like.error': 'Errore nel mettere like',
    'dislike.added': 'Dislike aggiunto!',
    'dislike.removed': 'Dislike rimosso',
    'dislike.error': 'Errore nel mettere dislike',
    'favorite.added': 'Aggiunto ai preferiti!',
    'favorite.removed': 'Rimosso dai preferiti',
    'favorite.error': 'Errore nella gestione preferiti',
    
    // Filters
    'filter.title': 'Filtri & Impostazioni',
    'filter.rating': 'Rating Contenuti',
    'filter.rating.safe': 'Solo Safe',
    'filter.rating.safe.desc': 'Mostra solo contenuti safe',
    'filter.rating.sq': 'Safe + Questionable',
    'filter.rating.sq.desc': 'Contenuti safe e questionable',
    'filter.rating.all': 'Tutti i rating',
    'filter.rating.all.desc': 'Mostra tutti i contenuti',
    'filter.rating.explicit': 'Solo Explicit',
    'filter.rating.explicit.desc': 'Mostra solo contenuti explicit',
    'filter.media': 'Tipo Media',
    'filter.media.all': 'Tutti',
    'filter.media.image': 'Solo Immagini',
    'filter.media.video': 'Solo Video',
    
    // Theme
    'theme.color': 'Colore Tema',
    'theme.mode': 'Modalità Tema',
    'theme.dark': 'Scuro',
    'theme.light': 'Chiaro',
    'theme.system': 'Sistema',
    
    // Advanced settings
    'settings.advanced': 'Impostazioni Avanzate',
    'settings.storage': 'Limite Archiviazione',
    'settings.storage.desc': 'Spazio massimo per cache contenuti',
    'settings.storage.current': 'Utilizzo attuale',
    'settings.storage.clear': 'Svuota Cache',
    'settings.storage.cleared': 'Cache svuotata',
    
    // Saved searches
    'saved.title': 'Ricerche Salvate',
    'saved.save': 'Salva ricerca attuale',
    'saved.empty': 'Inserisci dei tag prima di salvare',
    'saved.empty.list': 'Nessuna ricerca salvata',
    'saved.added': 'Ricerca salvata!',
    'saved.removed': 'Ricerca eliminata',
    'saved.renamed': 'Ricerca rinominata',
    'saved.overwritten': 'Ricerca sovrascritta!',
    'saved.overwrite': 'Sovrascrivi',
    
    // Info
    'info.title': 'Informazioni',
    'info.artists': 'Artisti',
    'info.characters': 'Personaggi',
    'info.tags': 'Tag',
    'info.score': 'Punteggio',
    'info.favorites': 'Preferiti',
    
    // Loading/States
    'loading.videos': 'Caricamento video...',
    'loading.posts': 'Caricamento post...',
    'loading.error': 'Errore di caricamento',
    'empty.videos': 'Nessun video trovato',
    'empty.posts': 'Nessun post trovato',
    'error.connection': 'Errore di connessione',
    'error.retry': 'Riprova',
    
    // Guest
    'guest': 'Ospite',
    'guest.login.required': 'Accedi per questa funzione',
  },
  en: {
    // Greetings
    'greeting.morning': 'Good morning',
    'greeting.afternoon': 'Good afternoon',
    'greeting.evening': 'Good evening',
    'greeting.hello': 'Hello',
    'greeting.welcome': 'Welcome back to e621 Gallery',
    
    // Navigation
    'nav.gallery': 'Gallery',
    'nav.shorts': 'Shorts',
    'nav.favorites': 'Favorites',
    
    // Actions
    'action.download': 'Download',
    'action.download.opened': 'Download opened in new tab',
    'action.download.unavailable': 'Download not available',
    'action.search': 'Search',
    'action.search.placeholder': 'Search tags...',
    'action.refresh': 'Refresh',
    'action.refreshed': 'Gallery refreshed',
    'action.login': 'Login',
    'action.logout': 'Logout',
    'action.back': 'Back',
    'action.close': 'Close',
    
    // Likes/Favorites
    'like.added': 'Like added!',
    'like.removed': 'Like removed',
    'like.error': 'Error adding like',
    'dislike.added': 'Dislike added!',
    'dislike.removed': 'Dislike removed',
    'dislike.error': 'Error adding dislike',
    'favorite.added': 'Added to favorites!',
    'favorite.removed': 'Removed from favorites',
    'favorite.error': 'Error managing favorites',
    
    // Filters
    'filter.title': 'Filters & Settings',
    'filter.rating': 'Content Rating',
    'filter.rating.safe': 'Safe Only',
    'filter.rating.safe.desc': 'Show only safe content',
    'filter.rating.sq': 'Safe + Questionable',
    'filter.rating.sq.desc': 'Safe and questionable content',
    'filter.rating.all': 'All ratings',
    'filter.rating.all.desc': 'Show all content',
    'filter.rating.explicit': 'Explicit Only',
    'filter.rating.explicit.desc': 'Show only explicit content',
    'filter.media': 'Media Type',
    'filter.media.all': 'All',
    'filter.media.image': 'Images Only',
    'filter.media.video': 'Videos Only',
    
    // Theme
    'theme.color': 'Theme Color',
    'theme.mode': 'Theme Mode',
    'theme.dark': 'Dark',
    'theme.light': 'Light',
    'theme.system': 'System',
    
    // Advanced settings
    'settings.advanced': 'Advanced Settings',
    'settings.storage': 'Storage Limit',
    'settings.storage.desc': 'Maximum space for content cache',
    'settings.storage.current': 'Current usage',
    'settings.storage.clear': 'Clear Cache',
    'settings.storage.cleared': 'Cache cleared',
    
    // Saved searches
    'saved.title': 'Saved Searches',
    'saved.save': 'Save current search',
    'saved.empty': 'Enter some tags before saving',
    'saved.empty.list': 'No saved searches',
    'saved.added': 'Search saved!',
    'saved.removed': 'Search deleted',
    'saved.renamed': 'Search renamed',
    'saved.overwritten': 'Search overwritten!',
    'saved.overwrite': 'Overwrite',
    
    // Info
    'info.title': 'Information',
    'info.artists': 'Artists',
    'info.characters': 'Characters',
    'info.tags': 'Tags',
    'info.score': 'Score',
    'info.favorites': 'Favorites',
    
    // Loading/States
    'loading.videos': 'Loading videos...',
    'loading.posts': 'Loading posts...',
    'loading.error': 'Loading error',
    'empty.videos': 'No videos found',
    'empty.posts': 'No posts found',
    'error.connection': 'Connection error',
    'error.retry': 'Retry',
    
    // Guest
    'guest': 'Guest',
    'guest.login.required': 'Login required for this feature',
  },
  es: {
    'greeting.morning': 'Buenos días',
    'greeting.afternoon': 'Buenas tardes',
    'greeting.evening': 'Buenas noches',
    'greeting.hello': 'Hola',
    'greeting.welcome': 'Bienvenido a e621 Gallery',
    'nav.gallery': 'Galería',
    'nav.shorts': 'Shorts',
    'nav.favorites': 'Favoritos',
    'action.download': 'Descargar',
    'action.download.opened': 'Descarga abierta en nueva pestaña',
    'action.download.unavailable': 'Descarga no disponible',
    'action.search': 'Buscar',
    'action.search.placeholder': 'Buscar tags...',
    'action.refresh': 'Actualizar',
    'action.refreshed': 'Galería actualizada',
    'action.login': 'Iniciar sesión',
    'action.logout': 'Cerrar sesión',
    'action.back': 'Atrás',
    'action.close': 'Cerrar',
    'like.added': '¡Like añadido!',
    'like.removed': 'Like eliminado',
    'like.error': 'Error al dar like',
    'dislike.added': '¡Dislike añadido!',
    'dislike.removed': 'Dislike eliminado',
    'dislike.error': 'Error al dar dislike',
    'favorite.added': '¡Añadido a favoritos!',
    'favorite.removed': 'Eliminado de favoritos',
    'favorite.error': 'Error gestionando favoritos',
    'filter.title': 'Filtros y Ajustes',
    'filter.rating': 'Clasificación',
    'filter.rating.safe': 'Solo Safe',
    'filter.rating.safe.desc': 'Mostrar solo contenido safe',
    'filter.rating.sq': 'Safe + Questionable',
    'filter.rating.sq.desc': 'Contenido safe y questionable',
    'filter.rating.all': 'Todas las clasificaciones',
    'filter.rating.all.desc': 'Mostrar todo el contenido',
    'filter.rating.explicit': 'Solo Explicit',
    'filter.rating.explicit.desc': 'Mostrar solo contenido explicit',
    'filter.media': 'Tipo de Media',
    'filter.media.all': 'Todos',
    'filter.media.image': 'Solo Imágenes',
    'filter.media.video': 'Solo Videos',
    'theme.color': 'Color del Tema',
    'theme.mode': 'Modo del Tema',
    'theme.dark': 'Oscuro',
    'theme.light': 'Claro',
    'theme.system': 'Sistema',
    'settings.advanced': 'Ajustes Avanzados',
    'settings.storage': 'Límite de Almacenamiento',
    'settings.storage.desc': 'Espacio máximo para caché',
    'settings.storage.current': 'Uso actual',
    'settings.storage.clear': 'Limpiar Caché',
    'settings.storage.cleared': 'Caché limpiada',
    'saved.title': 'Búsquedas Guardadas',
    'saved.save': 'Guardar búsqueda actual',
    'saved.empty': 'Ingresa algunos tags antes de guardar',
    'saved.empty.list': 'Sin búsquedas guardadas',
    'saved.added': '¡Búsqueda guardada!',
    'saved.removed': 'Búsqueda eliminada',
    'saved.renamed': 'Búsqueda renombrada',
    'saved.overwritten': '¡Búsqueda sobrescrita!',
    'saved.overwrite': 'Sobrescribir',
    'info.title': 'Información',
    'info.artists': 'Artistas',
    'info.characters': 'Personajes',
    'info.tags': 'Tags',
    'info.score': 'Puntuación',
    'info.favorites': 'Favoritos',
    'loading.videos': 'Cargando videos...',
    'loading.posts': 'Cargando posts...',
    'loading.error': 'Error de carga',
    'empty.videos': 'No se encontraron videos',
    'empty.posts': 'No se encontraron posts',
    'error.connection': 'Error de conexión',
    'error.retry': 'Reintentar',
    'guest': 'Invitado',
    'guest.login.required': 'Inicia sesión para esta función',
  },
  fr: {
    'greeting.morning': 'Bonjour',
    'greeting.afternoon': 'Bon après-midi',
    'greeting.evening': 'Bonsoir',
    'greeting.hello': 'Salut',
    'greeting.welcome': 'Bienvenue sur e621 Gallery',
    'nav.gallery': 'Galerie',
    'nav.shorts': 'Shorts',
    'nav.favorites': 'Favoris',
    'action.download': 'Télécharger',
    'action.download.opened': 'Téléchargement ouvert dans un nouvel onglet',
    'action.download.unavailable': 'Téléchargement non disponible',
    'action.search': 'Rechercher',
    'action.search.placeholder': 'Rechercher des tags...',
    'action.refresh': 'Actualiser',
    'action.refreshed': 'Galerie actualisée',
    'action.login': 'Connexion',
    'action.logout': 'Déconnexion',
    'action.back': 'Retour',
    'action.close': 'Fermer',
    'like.added': 'Like ajouté!',
    'like.removed': 'Like retiré',
    'like.error': 'Erreur lors du like',
    'dislike.added': 'Dislike ajouté!',
    'dislike.removed': 'Dislike retiré',
    'dislike.error': 'Erreur lors du dislike',
    'favorite.added': 'Ajouté aux favoris!',
    'favorite.removed': 'Retiré des favoris',
    'favorite.error': 'Erreur de gestion des favoris',
    'filter.title': 'Filtres et Paramètres',
    'filter.rating': 'Classification',
    'filter.rating.safe': 'Safe uniquement',
    'filter.rating.safe.desc': 'Afficher uniquement le contenu safe',
    'filter.rating.sq': 'Safe + Questionable',
    'filter.rating.sq.desc': 'Contenu safe et questionable',
    'filter.rating.all': 'Toutes les classifications',
    'filter.rating.all.desc': 'Afficher tout le contenu',
    'filter.rating.explicit': 'Explicit uniquement',
    'filter.rating.explicit.desc': 'Afficher uniquement le contenu explicit',
    'filter.media': 'Type de Média',
    'filter.media.all': 'Tous',
    'filter.media.image': 'Images uniquement',
    'filter.media.video': 'Vidéos uniquement',
    'theme.color': 'Couleur du Thème',
    'theme.mode': 'Mode du Thème',
    'theme.dark': 'Sombre',
    'theme.light': 'Clair',
    'theme.system': 'Système',
    'settings.advanced': 'Paramètres Avancés',
    'settings.storage': 'Limite de Stockage',
    'settings.storage.desc': 'Espace maximum pour le cache',
    'settings.storage.current': 'Utilisation actuelle',
    'settings.storage.clear': 'Vider le Cache',
    'settings.storage.cleared': 'Cache vidé',
    'saved.title': 'Recherches Sauvegardées',
    'saved.save': 'Sauvegarder la recherche actuelle',
    'saved.empty': 'Entrez des tags avant de sauvegarder',
    'saved.empty.list': 'Aucune recherche sauvegardée',
    'saved.added': 'Recherche sauvegardée!',
    'saved.removed': 'Recherche supprimée',
    'saved.renamed': 'Recherche renommée',
    'saved.overwritten': 'Recherche écrasée!',
    'saved.overwrite': 'Écraser',
    'info.title': 'Informations',
    'info.artists': 'Artistes',
    'info.characters': 'Personnages',
    'info.tags': 'Tags',
    'info.score': 'Score',
    'info.favorites': 'Favoris',
    'loading.videos': 'Chargement des vidéos...',
    'loading.posts': 'Chargement des posts...',
    'loading.error': 'Erreur de chargement',
    'empty.videos': 'Aucune vidéo trouvée',
    'empty.posts': 'Aucun post trouvé',
    'error.connection': 'Erreur de connexion',
    'error.retry': 'Réessayer',
    'guest': 'Invité',
    'guest.login.required': 'Connexion requise pour cette fonction',
  },
  de: {
    'greeting.morning': 'Guten Morgen',
    'greeting.afternoon': 'Guten Tag',
    'greeting.evening': 'Guten Abend',
    'greeting.hello': 'Hallo',
    'greeting.welcome': 'Willkommen bei e621 Gallery',
    'nav.gallery': 'Galerie',
    'nav.shorts': 'Shorts',
    'nav.favorites': 'Favoriten',
    'action.download': 'Herunterladen',
    'action.download.opened': 'Download in neuem Tab geöffnet',
    'action.download.unavailable': 'Download nicht verfügbar',
    'action.search': 'Suchen',
    'action.search.placeholder': 'Tags suchen...',
    'action.refresh': 'Aktualisieren',
    'action.refreshed': 'Galerie aktualisiert',
    'action.login': 'Anmelden',
    'action.logout': 'Abmelden',
    'action.back': 'Zurück',
    'action.close': 'Schließen',
    'like.added': 'Like hinzugefügt!',
    'like.removed': 'Like entfernt',
    'like.error': 'Fehler beim Liken',
    'dislike.added': 'Dislike hinzugefügt!',
    'dislike.removed': 'Dislike entfernt',
    'dislike.error': 'Fehler beim Disliken',
    'favorite.added': 'Zu Favoriten hinzugefügt!',
    'favorite.removed': 'Aus Favoriten entfernt',
    'favorite.error': 'Fehler bei Favoritenverwaltung',
    'filter.title': 'Filter & Einstellungen',
    'filter.rating': 'Inhaltsbewertung',
    'filter.rating.safe': 'Nur Safe',
    'filter.rating.safe.desc': 'Nur sichere Inhalte anzeigen',
    'filter.rating.sq': 'Safe + Questionable',
    'filter.rating.sq.desc': 'Sichere und fragwürdige Inhalte',
    'filter.rating.all': 'Alle Bewertungen',
    'filter.rating.all.desc': 'Alle Inhalte anzeigen',
    'filter.rating.explicit': 'Nur Explicit',
    'filter.rating.explicit.desc': 'Nur explizite Inhalte anzeigen',
    'filter.media': 'Medientyp',
    'filter.media.all': 'Alle',
    'filter.media.image': 'Nur Bilder',
    'filter.media.video': 'Nur Videos',
    'theme.color': 'Themenfarbe',
    'theme.mode': 'Themenmodus',
    'theme.dark': 'Dunkel',
    'theme.light': 'Hell',
    'theme.system': 'System',
    'settings.advanced': 'Erweiterte Einstellungen',
    'settings.storage': 'Speicherlimit',
    'settings.storage.desc': 'Maximaler Speicher für Cache',
    'settings.storage.current': 'Aktuelle Nutzung',
    'settings.storage.clear': 'Cache leeren',
    'settings.storage.cleared': 'Cache geleert',
    'saved.title': 'Gespeicherte Suchen',
    'saved.save': 'Aktuelle Suche speichern',
    'saved.empty': 'Geben Sie Tags ein, bevor Sie speichern',
    'saved.empty.list': 'Keine gespeicherten Suchen',
    'saved.added': 'Suche gespeichert!',
    'saved.removed': 'Suche gelöscht',
    'saved.renamed': 'Suche umbenannt',
    'saved.overwritten': 'Suche überschrieben!',
    'saved.overwrite': 'Überschreiben',
    'info.title': 'Informationen',
    'info.artists': 'Künstler',
    'info.characters': 'Charaktere',
    'info.tags': 'Tags',
    'info.score': 'Punktzahl',
    'info.favorites': 'Favoriten',
    'loading.videos': 'Videos werden geladen...',
    'loading.posts': 'Beiträge werden geladen...',
    'loading.error': 'Ladefehler',
    'empty.videos': 'Keine Videos gefunden',
    'empty.posts': 'Keine Beiträge gefunden',
    'error.connection': 'Verbindungsfehler',
    'error.retry': 'Erneut versuchen',
    'guest': 'Gast',
    'guest.login.required': 'Anmeldung für diese Funktion erforderlich',
  },
  pt: {
    'greeting.morning': 'Bom dia',
    'greeting.afternoon': 'Boa tarde',
    'greeting.evening': 'Boa noite',
    'greeting.hello': 'Olá',
    'greeting.welcome': 'Bem-vindo ao e621 Gallery',
    'nav.gallery': 'Galeria',
    'nav.shorts': 'Shorts',
    'nav.favorites': 'Favoritos',
    'action.download': 'Baixar',
    'action.download.opened': 'Download aberto em nova aba',
    'action.download.unavailable': 'Download não disponível',
    'action.search': 'Pesquisar',
    'action.search.placeholder': 'Pesquisar tags...',
    'action.refresh': 'Atualizar',
    'action.refreshed': 'Galeria atualizada',
    'action.login': 'Entrar',
    'action.logout': 'Sair',
    'action.back': 'Voltar',
    'action.close': 'Fechar',
    'like.added': 'Like adicionado!',
    'like.removed': 'Like removido',
    'like.error': 'Erro ao curtir',
    'dislike.added': 'Dislike adicionado!',
    'dislike.removed': 'Dislike removido',
    'dislike.error': 'Erro ao descurtir',
    'favorite.added': 'Adicionado aos favoritos!',
    'favorite.removed': 'Removido dos favoritos',
    'favorite.error': 'Erro ao gerenciar favoritos',
    'filter.title': 'Filtros e Configurações',
    'filter.rating': 'Classificação',
    'filter.rating.safe': 'Apenas Safe',
    'filter.rating.safe.desc': 'Mostrar apenas conteúdo safe',
    'filter.rating.sq': 'Safe + Questionable',
    'filter.rating.sq.desc': 'Conteúdo safe e questionable',
    'filter.rating.all': 'Todas as classificações',
    'filter.rating.all.desc': 'Mostrar todo o conteúdo',
    'filter.rating.explicit': 'Apenas Explicit',
    'filter.rating.explicit.desc': 'Mostrar apenas conteúdo explicit',
    'filter.media': 'Tipo de Mídia',
    'filter.media.all': 'Todos',
    'filter.media.image': 'Apenas Imagens',
    'filter.media.video': 'Apenas Vídeos',
    'theme.color': 'Cor do Tema',
    'theme.mode': 'Modo do Tema',
    'theme.dark': 'Escuro',
    'theme.light': 'Claro',
    'theme.system': 'Sistema',
    'settings.advanced': 'Configurações Avançadas',
    'settings.storage': 'Limite de Armazenamento',
    'settings.storage.desc': 'Espaço máximo para cache',
    'settings.storage.current': 'Uso atual',
    'settings.storage.clear': 'Limpar Cache',
    'settings.storage.cleared': 'Cache limpo',
    'saved.title': 'Pesquisas Salvas',
    'saved.save': 'Salvar pesquisa atual',
    'saved.empty': 'Digite algumas tags antes de salvar',
    'saved.empty.list': 'Nenhuma pesquisa salva',
    'saved.added': 'Pesquisa salva!',
    'saved.removed': 'Pesquisa excluída',
    'saved.renamed': 'Pesquisa renomeada',
    'saved.overwritten': 'Pesquisa sobrescrita!',
    'saved.overwrite': 'Sobrescrever',
    'info.title': 'Informações',
    'info.artists': 'Artistas',
    'info.characters': 'Personagens',
    'info.tags': 'Tags',
    'info.score': 'Pontuação',
    'info.favorites': 'Favoritos',
    'loading.videos': 'Carregando vídeos...',
    'loading.posts': 'Carregando posts...',
    'loading.error': 'Erro de carregamento',
    'empty.videos': 'Nenhum vídeo encontrado',
    'empty.posts': 'Nenhum post encontrado',
    'error.connection': 'Erro de conexão',
    'error.retry': 'Tentar novamente',
    'guest': 'Visitante',
    'guest.login.required': 'Login necessário para esta função',
  },
};

function getSystemLanguage(): Language {
  const browserLang = navigator.language.toLowerCase();
  const langCode = browserLang.split('-')[0];
  
  if (langCode in translations) {
    return langCode as Language;
  }
  
  // Default to Italian
  return 'it';
}

export function useLanguage() {
  const [language, setLanguage] = useState<Language>(getSystemLanguage);

  useEffect(() => {
    // Listen for language changes
    const handleLanguageChange = () => {
      setLanguage(getSystemLanguage());
    };

    window.addEventListener('languagechange', handleLanguageChange);
    return () => window.removeEventListener('languagechange', handleLanguageChange);
  }, []);

  const t = (key: string): string => {
    return translations[language][key] || translations['en'][key] || key;
  };

  const getGreeting = (): string => {
    const hour = new Date().getHours();
    if (hour < 12) return t('greeting.morning');
    if (hour < 18) return t('greeting.afternoon');
    return t('greeting.evening');
  };

  return { language, t, getGreeting };
}

export { translations };
